version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        update-types: [minor, patch]
