#!/bin/sh
# framebeam-hub postrm: purge removes the configuration only. The data directory (database, saves, ROM library)
# and the system user are never deleted by the package.
set -e

case "$1" in
  remove|purge)
    if [ -d /run/systemd/system ]; then systemctl daemon-reload || true; fi
    ;;
esac
case "$1" in
  purge)
    rm -rf /etc/framebeam
    ;;
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;
  *)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

exit 0
