#!/usr/bin/env bash
# Generates server/THIRD-PARTY-NOTICES.txt: license texts of the Go modules compiled into framebeam-hub.
# Usage: scripts/gen-hub-notices.sh [--check]
#   --check  regenerate to a temp file and diff against the committed file (exit 1 when stale).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/server/THIRD-PARTY-NOTICES.txt"
export GOTOOLCHAIN=local CGO_ENABLED=0

die() { echo "error: $*" >&2; exit 1; }

generate() {
  local dest="$1" mainmod mods line path ver dir f found
  cd "$ROOT/server"
  mainmod="$(go list -m)"
  mods="$(go list -deps -f '{{with .Module}}{{.Path}} {{.Version}}{{end}}' ./cmd/framebeam-hub \
    | awk -v m="$mainmod" 'NF == 2 && $1 != m' | LC_ALL=C sort -u)" || return 1
  [ -n "$mods" ] || die "no third-party modules found"
  {
    echo "FrameBeam Hub"
    echo "Copyright (C) 2026 Fabio and FrameBeam contributors"
    echo "Licensed under GPL-3.0-or-later (see LICENSE)."
    echo
    echo "This file lists the third-party Go modules compiled into framebeam-hub with their full license texts."
    echo "Generated by scripts/gen-hub-notices.sh; do not edit."
    while read -r path ver; do
      [ -n "$path" ] || continue
      dir="$(go list -m -f '{{.Dir}}' "$path@$ver" 2>/dev/null || true)"
      [ -n "$dir" ] && [ -d "$dir" ] || dir="$(go list -m -f '{{.Dir}}' "$path")"
      [ -d "$dir" ] || die "module directory not found: $path@$ver (run 'go mod download')"
      found=""
      for f in LICENSE LICENSE.txt LICENSE.md COPYING COPYING.txt; do
        [ -f "$dir/$f" ] && { found="$dir/$f"; break; }
      done
      [ -n "$found" ] || die "no license file in $path@$ver"
      echo
      echo "================================================================================"
      echo "$path@$ver"
      echo "================================================================================"
      echo
      cat "$found"
    done <<<"$mods"
    [ -f "$(go env GOROOT)/LICENSE" ] || die "Go LICENSE not found"
    echo
    echo "================================================================================"
    echo "Go standard library"
    echo "================================================================================"
    echo
    cat "$(go env GOROOT)/LICENSE"
  } >"$dest"
}

case "${1:-}" in
  "") generate "$OUT" ;;
  --check)
    tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
    generate "$tmp"
    diff -u "$OUT" "$tmp" >/dev/null 2>&1 || { echo "server/THIRD-PARTY-NOTICES.txt is stale: run 'make notices' and commit"; exit 1; }
    ;;
  *) die "usage: gen-hub-notices.sh [--check]" ;;
esac
