//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    = "bearerAuth.Scopes"
	PollTokenAuthScopes = "pollTokenAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeBadRequest          ErrorCode = "bad_request"
	ErrorCodeCapabilityMissing   ErrorCode = "capability_missing"
	ErrorCodeConflict            ErrorCode = "conflict"
	ErrorCodeCoreMissing         ErrorCode = "core_missing"
	ErrorCodeCoreVersionMismatch ErrorCode = "core_version_mismatch"
	ErrorCodeDeviceRevoked       ErrorCode = "device_revoked"
	ErrorCodeForbidden           ErrorCode = "forbidden"
	ErrorCodeHubTooOld           ErrorCode = "hub_too_old"
	ErrorCodeInternal            ErrorCode = "internal"
	ErrorCodeInvalidCredentials  ErrorCode = "invalid_credentials"
	ErrorCodeNotFound            ErrorCode = "not_found"
	ErrorCodePairingDenied       ErrorCode = "pairing_denied"
	ErrorCodePairingExpired      ErrorCode = "pairing_expired"
	ErrorCodePairingPending      ErrorCode = "pairing_pending"
	ErrorCodePayloadTooLarge     ErrorCode = "payload_too_large"
	ErrorCodePlayerTooOld        ErrorCode = "player_too_old"
	ErrorCodeRateLimited         ErrorCode = "rate_limited"
	ErrorCodeSaveConflict        ErrorCode = "save_conflict"
	ErrorCodeSaveConflictStale   ErrorCode = "save_conflict_stale"
	ErrorCodeUnauthorized        ErrorCode = "unauthorized"
)

// Defines values for HandshakeProblemCode.
const (
	HandshakeProblemCodeCapabilityMissing   HandshakeProblemCode = "capability_missing"
	HandshakeProblemCodeCoreMissing         HandshakeProblemCode = "core_missing"
	HandshakeProblemCodeCoreVersionMismatch HandshakeProblemCode = "core_version_mismatch"
	HandshakeProblemCodeHubTooOld           HandshakeProblemCode = "hub_too_old"
	HandshakeProblemCodePlayerTooOld        HandshakeProblemCode = "player_too_old"
)

// Defines values for PairingRequestAcceptedStatus.
const (
	PairingRequestAcceptedStatusPending PairingRequestAcceptedStatus = "pending"
)

// Defines values for PairingStatusStatus.
const (
	PairingStatusStatusApproved PairingStatusStatus = "approved"
	PairingStatusStatusDenied   PairingStatusStatus = "denied"
	PairingStatusStatusExpired  PairingStatusStatus = "expired"
	PairingStatusStatusPending  PairingStatusStatus = "pending"
)

// Defines values for SaveConflictStatus.
const (
	Open          SaveConflictStatus = "open"
	ResolvedHub   SaveConflictStatus = "resolved_hub"
	ResolvedLocal SaveConflictStatus = "resolved_local"
)

// Defines values for SaveHistoryReason.
const (
	BeforeConflictResolution SaveHistoryReason = "before_conflict_resolution"
	ConflictUpload           SaveHistoryReason = "conflict_upload"
	DeviceChange             SaveHistoryReason = "device_change"
	ManualSnapshot           SaveHistoryReason = "manual_snapshot"
	SessionEnd               SaveHistoryReason = "session_end"
)

// Defines values for SaveResolveRequestResolution.
const (
	UseHub   SaveResolveRequestResolution = "use_hub"
	UseLocal SaveResolveRequestResolution = "use_local"
)

// Defines values for SaveSyncReason.
const (
	Checkpoint      SaveSyncReason = "checkpoint"
	Final           SaveSyncReason = "final"
	FinalSessionEnd SaveSyncReason = "final_session_end"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// CoreInfo defines model for CoreInfo.
type CoreInfo struct {
	Id      string `json:"id"`
	Version string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Game defines model for Game.
type Game struct {
	AddedAt time.Time          `json:"added_at"`
	Id      openapi_types.UUID `json:"id"`
	Rom     RomInfo            `json:"rom"`
	System  string             `json:"system"`
	Title   string             `json:"title"`

	// UploadedBy Hub-local user ID
	UploadedBy string `json:"uploaded_by"`
}

// HandshakeProblem defines model for HandshakeProblem.
type HandshakeProblem struct {
	Code   HandshakeProblemCode `json:"code"`
	CoreId *string              `json:"core_id,omitempty"`
	Detail string               `json:"detail"`
}

// HandshakeProblemCode defines model for HandshakeProblem.Code.
type HandshakeProblemCode string

// HandshakeRequest defines model for HandshakeRequest.
type HandshakeRequest struct {
	Arch                 string                 `json:"arch"`
	Audio                HandshakeRequest_Audio `json:"audio"`
	Cores                []CoreInfo             `json:"cores"`
	Input                HandshakeRequest_Input `json:"input"`
	MinProtocolVersion   int                    `json:"min_protocol_version"`
	Platform             string                 `json:"platform"`
	PlayerVersion        string                 `json:"player_version"`
	ProtocolVersion      int                    `json:"protocol_version"`
	Video                HandshakeRequest_Video `json:"video"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeRequest_Audio defines model for HandshakeRequest.Audio.
type HandshakeRequest_Audio struct {
	Opus                 bool                   `json:"opus"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeRequest_Input defines model for HandshakeRequest.Input.
type HandshakeRequest_Input struct {
	Gamepad              bool                   `json:"gamepad"`
	Keyboard             bool                   `json:"keyboard"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeRequest_Video defines model for HandshakeRequest.Video.
type HandshakeRequest_Video struct {
	Encoders             []string               `json:"encoders"`
	H264Decode           bool                   `json:"h264_decode"`
	H264Encode           bool                   `json:"h264_encode"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeResponse defines model for HandshakeResponse.
type HandshakeResponse struct {
	Compatible bool `json:"compatible"`

	// Features Optional Hub feature flags (additive, protocol_version unchanged). `saves_v1` = save sync API.
	Features           *[]string          `json:"features,omitempty"`
	HubVersion         string             `json:"hub_version"`
	MinProtocolVersion int                `json:"min_protocol_version"`
	Problems           []HandshakeProblem `json:"problems"`
	ProtocolVersion    int                `json:"protocol_version"`
}

// HubInfo defines model for HubInfo.
type HubInfo struct {
	ApiBase            string             `json:"api_base"`
	HubId              openapi_types.UUID `json:"hub_id"`
	HubVersion         string             `json:"hub_version"`
	MinProtocolVersion int                `json:"min_protocol_version"`
	Name               string             `json:"name"`
	ProtocolVersion    int                `json:"protocol_version"`
}

// PairingRequestAccepted defines model for PairingRequestAccepted.
type PairingRequestAccepted struct {
	// ExpiresIn Seconds
	ExpiresIn int `json:"expires_in"`

	// PollToken Prefix fbp_
	PollToken string                       `json:"poll_token"`
	RequestId openapi_types.UUID           `json:"request_id"`
	Status    PairingRequestAcceptedStatus `json:"status"`
}

// PairingRequestAcceptedStatus defines model for PairingRequestAccepted.Status.
type PairingRequestAcceptedStatus string

// PairingRequestCreate defines model for PairingRequestCreate.
type PairingRequestCreate struct {
	Arch            string             `json:"arch"`
	DeviceId        openapi_types.UUID `json:"device_id"`
	DeviceName      string             `json:"device_name"`
	Platform        string             `json:"platform"`
	PlayerVersion   string             `json:"player_version"`
	ProtocolVersion int                `json:"protocol_version"`
}

// PairingStatus defines model for PairingStatus.
type PairingStatus struct {
	// DeviceCredential Prefix fbd_; only when approved, once
	DeviceCredential *string `json:"device_credential,omitempty"`

	// HubId Only when approved (once)
	HubId  *openapi_types.UUID `json:"hub_id,omitempty"`
	Status PairingStatusStatus `json:"status"`

	// UserId Hub-local user ID; only when approved
	UserId *string `json:"user_id,omitempty"`
}

// PairingStatusStatus defines model for PairingStatus.Status.
type PairingStatusStatus string

// RomInfo defines model for RomInfo.
type RomInfo struct {
	Filename string `json:"filename"`
	Sha256   string `json:"sha256"`
	Size     int64  `json:"size"`
}

// SaveCheckpoint Current checkpoint of a slot (one opaque blob).
type SaveCheckpoint struct {
	CreatedAt  time.Time          `json:"created_at"`
	DeviceId   openapi_types.UUID `json:"device_id"`
	DeviceName string             `json:"device_name"`
	Reason     SaveSyncReason     `json:"reason"`

	// Revision Per-slot checkpoint counter ("Rev N")
	Revision int    `json:"revision"`
	Sha256   string `json:"sha256"`
	Size     int64  `json:"size"`
}

// SaveConflict defines model for SaveConflict.
type SaveConflict struct {
	CreatedAt  time.Time           `json:"created_at"`
	GameId     openapi_types.UUID  `json:"game_id"`
	Hub        SaveConflictHubSide `json:"hub"`
	Id         string              `json:"id"`
	ResolvedAt *time.Time          `json:"resolved_at"`

	// ResolvedBy Hub-local user ID or device ID of the resolver
	ResolvedBy *string                   `json:"resolved_by"`
	Secured    SaveConflictSecuredUpload `json:"secured"`
	Slot       string                    `json:"slot"`
	Status     SaveConflictStatus        `json:"status"`
}

// SaveConflictStatus defines model for SaveConflict.Status.
type SaveConflictStatus string

// SaveConflictError Error body of the upload 409 (`save_conflict`) carrying the conflict.
type SaveConflictError struct {
	Conflict SaveConflict `json:"conflict"`
	Error    struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// SaveConflictHubSide defines model for SaveConflictHubSide.
type SaveConflictHubSide struct {
	CreatedAt  time.Time          `json:"created_at"`
	DeviceId   openapi_types.UUID `json:"device_id"`
	DeviceName string             `json:"device_name"`
	Revision   int                `json:"revision"`
	Sha256     string             `json:"sha256"`
}

// SaveConflictSecuredUpload defines model for SaveConflictSecuredUpload.
type SaveConflictSecuredUpload struct {
	BaseRevision int                `json:"base_revision"`
	CreatedAt    time.Time          `json:"created_at"`
	DeviceId     openapi_types.UUID `json:"device_id"`
	DeviceName   string             `json:"device_name"`
	Sha256       string             `json:"sha256"`

	// Version History version holding the secured upload
	Version int `json:"version"`
}

// SaveHistoryReason defines model for SaveHistoryReason.
type SaveHistoryReason string

// SaveHistoryVersion Permanent history version with its own per-slot counter ("vN").
type SaveHistoryVersion struct {
	CreatedAt  time.Time          `json:"created_at"`
	DeviceId   openapi_types.UUID `json:"device_id"`
	DeviceName string             `json:"device_name"`
	Reason     SaveHistoryReason  `json:"reason"`

	// Revision Checkpoint revision captured
	Revision int    `json:"revision"`
	Sha256   string `json:"sha256"`
	Size     int64  `json:"size"`
	Version  int    `json:"version"`
}

// SaveResolveRequest defines model for SaveResolveRequest.
type SaveResolveRequest struct {
	// ExpectedRevision Current checkpoint revision the caller saw
	ExpectedRevision int                          `json:"expected_revision"`
	Resolution       SaveResolveRequestResolution `json:"resolution"`
}

// SaveResolveRequestResolution defines model for SaveResolveRequest.Resolution.
type SaveResolveRequestResolution string

// SaveSlot defines model for SaveSlot.
type SaveSlot struct {
	// Current Current checkpoint of a slot (one opaque blob).
	Current       SaveCheckpoint     `json:"current"`
	GameId        openapi_types.UUID `json:"game_id"`
	OpenConflicts []SaveConflict     `json:"open_conflicts"`
	Slot          string             `json:"slot"`
}

// SaveSlotSummary defines model for SaveSlotSummary.
type SaveSlotSummary struct {
	// Current Current checkpoint of a slot (one opaque blob).
	Current           SaveCheckpoint     `json:"current"`
	GameId            openapi_types.UUID `json:"game_id"`
	OpenConflictCount int                `json:"open_conflict_count"`
	Slot              string             `json:"slot"`
}

// SaveSyncReason defines model for SaveSyncReason.
type SaveSyncReason string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	DeviceCredential string             `json:"device_credential"`
	DeviceId         openapi_types.UUID `json:"device_id"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Prefix fba_
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds
	ExpiresIn int                    `json:"expires_in"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// GameId defines model for GameId.
type GameId = openapi_types.UUID

// SaveSlotName defines model for SaveSlotName.
type SaveSlotName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PutSaveParams defines parameters for PutSave.
type PutSaveParams struct {
	// XFrameBeamBaseRevision Checkpoint revision the upload is based on; 0 = the Player had no Hub save.
	XFrameBeamBaseRevision int `json:"X-FrameBeam-Base-Revision"`

	// XFrameBeamContentSHA256 Lowercase hex SHA-256 of the body; verified by the Hub.
	XFrameBeamContentSHA256 string         `json:"X-FrameBeam-Content-SHA256"`
	XFrameBeamSyncReason    SaveSyncReason `json:"X-FrameBeam-Sync-Reason"`
}

// DownloadRomParams defines parameters for DownloadRom.
type DownloadRomParams struct {
	Range *string `json:"Range,omitempty"`
}

// CreateAccessTokenJSONRequestBody defines body for CreateAccessToken for application/json ContentType.
type CreateAccessTokenJSONRequestBody = TokenRequest

// ResolveSaveConflictJSONRequestBody defines body for ResolveSaveConflict for application/json ContentType.
type ResolveSaveConflictJSONRequestBody = SaveResolveRequest

// PostHandshakeJSONRequestBody defines body for PostHandshake for application/json ContentType.
type PostHandshakeJSONRequestBody = HandshakeRequest

// CreatePairingRequestJSONRequestBody defines body for CreatePairingRequest for application/json ContentType.
type CreatePairingRequestJSONRequestBody = PairingRequestCreate

// Getter for additional properties for HandshakeRequest. Returns the specified
// element and whether it was found
func (a HandshakeRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest
func (a *HandshakeRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest to handle AdditionalProperties
func (a *HandshakeRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["arch"]; found {
		err = json.Unmarshal(raw, &a.Arch)
		if err != nil {
			return fmt.Errorf("error reading 'arch': %w", err)
		}
		delete(object, "arch")
	}

	if raw, found := object["audio"]; found {
		err = json.Unmarshal(raw, &a.Audio)
		if err != nil {
			return fmt.Errorf("error reading 'audio': %w", err)
		}
		delete(object, "audio")
	}

	if raw, found := object["cores"]; found {
		err = json.Unmarshal(raw, &a.Cores)
		if err != nil {
			return fmt.Errorf("error reading 'cores': %w", err)
		}
		delete(object, "cores")
	}

	if raw, found := object["input"]; found {
		err = json.Unmarshal(raw, &a.Input)
		if err != nil {
			return fmt.Errorf("error reading 'input': %w", err)
		}
		delete(object, "input")
	}

	if raw, found := object["min_protocol_version"]; found {
		err = json.Unmarshal(raw, &a.MinProtocolVersion)
		if err != nil {
			return fmt.Errorf("error reading 'min_protocol_version': %w", err)
		}
		delete(object, "min_protocol_version")
	}

	if raw, found := object["platform"]; found {
		err = json.Unmarshal(raw, &a.Platform)
		if err != nil {
			return fmt.Errorf("error reading 'platform': %w", err)
		}
		delete(object, "platform")
	}

	if raw, found := object["player_version"]; found {
		err = json.Unmarshal(raw, &a.PlayerVersion)
		if err != nil {
			return fmt.Errorf("error reading 'player_version': %w", err)
		}
		delete(object, "player_version")
	}

	if raw, found := object["protocol_version"]; found {
		err = json.Unmarshal(raw, &a.ProtocolVersion)
		if err != nil {
			return fmt.Errorf("error reading 'protocol_version': %w", err)
		}
		delete(object, "protocol_version")
	}

	if raw, found := object["video"]; found {
		err = json.Unmarshal(raw, &a.Video)
		if err != nil {
			return fmt.Errorf("error reading 'video': %w", err)
		}
		delete(object, "video")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest to handle AdditionalProperties
func (a HandshakeRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["arch"], err = json.Marshal(a.Arch)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'arch': %w", err)
	}

	object["audio"], err = json.Marshal(a.Audio)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'audio': %w", err)
	}

	if a.Cores != nil {
		object["cores"], err = json.Marshal(a.Cores)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cores': %w", err)
		}
	}

	object["input"], err = json.Marshal(a.Input)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'input': %w", err)
	}

	object["min_protocol_version"], err = json.Marshal(a.MinProtocolVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min_protocol_version': %w", err)
	}

	object["platform"], err = json.Marshal(a.Platform)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'platform': %w", err)
	}

	object["player_version"], err = json.Marshal(a.PlayerVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'player_version': %w", err)
	}

	object["protocol_version"], err = json.Marshal(a.ProtocolVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'protocol_version': %w", err)
	}

	object["video"], err = json.Marshal(a.Video)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'video': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HandshakeRequest_Audio. Returns the specified
// element and whether it was found
func (a HandshakeRequest_Audio) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest_Audio
func (a *HandshakeRequest_Audio) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest_Audio to handle AdditionalProperties
func (a *HandshakeRequest_Audio) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["opus"]; found {
		err = json.Unmarshal(raw, &a.Opus)
		if err != nil {
			return fmt.Errorf("error reading 'opus': %w", err)
		}
		delete(object, "opus")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest_Audio to handle AdditionalProperties
func (a HandshakeRequest_Audio) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["opus"], err = json.Marshal(a.Opus)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'opus': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HandshakeRequest_Input. Returns the specified
// element and whether it was found
func (a HandshakeRequest_Input) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest_Input
func (a *HandshakeRequest_Input) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest_Input to handle AdditionalProperties
func (a *HandshakeRequest_Input) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["gamepad"]; found {
		err = json.Unmarshal(raw, &a.Gamepad)
		if err != nil {
			return fmt.Errorf("error reading 'gamepad': %w", err)
		}
		delete(object, "gamepad")
	}

	if raw, found := object["keyboard"]; found {
		err = json.Unmarshal(raw, &a.Keyboard)
		if err != nil {
			return fmt.Errorf("error reading 'keyboard': %w", err)
		}
		delete(object, "keyboard")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest_Input to handle AdditionalProperties
func (a HandshakeRequest_Input) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["gamepad"], err = json.Marshal(a.Gamepad)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'gamepad': %w", err)
	}

	object["keyboard"], err = json.Marshal(a.Keyboard)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'keyboard': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HandshakeRequest_Video. Returns the specified
// element and whether it was found
func (a HandshakeRequest_Video) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest_Video
func (a *HandshakeRequest_Video) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest_Video to handle AdditionalProperties
func (a *HandshakeRequest_Video) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["encoders"]; found {
		err = json.Unmarshal(raw, &a.Encoders)
		if err != nil {
			return fmt.Errorf("error reading 'encoders': %w", err)
		}
		delete(object, "encoders")
	}

	if raw, found := object["h264_decode"]; found {
		err = json.Unmarshal(raw, &a.H264Decode)
		if err != nil {
			return fmt.Errorf("error reading 'h264_decode': %w", err)
		}
		delete(object, "h264_decode")
	}

	if raw, found := object["h264_encode"]; found {
		err = json.Unmarshal(raw, &a.H264Encode)
		if err != nil {
			return fmt.Errorf("error reading 'h264_encode': %w", err)
		}
		delete(object, "h264_encode")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest_Video to handle AdditionalProperties
func (a HandshakeRequest_Video) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Encoders != nil {
		object["encoders"], err = json.Marshal(a.Encoders)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'encoders': %w", err)
		}
	}

	object["h264_decode"], err = json.Marshal(a.H264Decode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'h264_decode': %w", err)
	}

	object["h264_encode"], err = json.Marshal(a.H264Encode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'h264_encode': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Hub info (no auth, grants no rights)
	// (GET /.well-known/framebeam)
	GetHubInfo(w http.ResponseWriter, r *http.Request)
	// Device revokes itself
	// (POST /api/v1/auth/revoke)
	RevokeSelf(w http.ResponseWriter, r *http.Request)
	// Exchange device credential for access token
	// (POST /api/v1/auth/token)
	CreateAccessToken(w http.ResponseWriter, r *http.Request)
	// Game library
	// (GET /api/v1/games)
	ListGames(w http.ResponseWriter, r *http.Request)
	// Single game
	// (GET /api/v1/games/{game_id})
	GetGame(w http.ResponseWriter, r *http.Request, gameId openapi_types.UUID)
	// Current checkpoint metadata and open conflicts of a slot
	// (GET /api/v1/games/{game_id}/saves/{slot})
	GetSaveSlot(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName)
	// Upload the save file (raw body) against a base revision
	// (PUT /api/v1/games/{game_id}/saves/{slot})
	PutSave(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName, params PutSaveParams)
	// Resolve an open save conflict
	// (POST /api/v1/games/{game_id}/saves/{slot}/conflicts/{conflict_id}/resolve)
	ResolveSaveConflict(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName, conflictId string)
	// Bytes of the current checkpoint
	// (GET /api/v1/games/{game_id}/saves/{slot}/content)
	DownloadSaveContent(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName)
	// Permanent history versions of a slot (newest first)
	// (GET /api/v1/games/{game_id}/saves/{slot}/history)
	ListSaveHistory(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName)
	// Bytes of a history version
	// (GET /api/v1/games/{game_id}/saves/{slot}/history/{version}/content)
	DownloadSaveHistoryContent(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName, version int)
	// Handshake with capability negotiation
	// (POST /api/v1/handshake)
	PostHandshake(w http.ResponseWriter, r *http.Request)
	// Submit pairing request (admin decides allow/deny)
	// (POST /api/v1/pairing/requests)
	CreatePairingRequest(w http.ResponseWriter, r *http.Request)
	// Poll pairing request status (bearer = poll_token)
	// (GET /api/v1/pairing/requests/{request_id})
	GetPairingRequest(w http.ResponseWriter, r *http.Request, requestId openapi_types.UUID)
	// ROM download (range support). Upload only via the admin web interface.
	// (GET /api/v1/roms/{sha256})
	DownloadRom(w http.ResponseWriter, r *http.Request, sha256 string, params DownloadRomParams)
	// Save slots of the authenticated device's user
	// (GET /api/v1/saves)
	ListSaves(w http.ResponseWriter, r *http.Request)
	// WSS upgrade (documentation only, implementation to follow)
	// (GET /api/v1/ws)
	ConnectWebSocket(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHubInfo operation middleware
func (siw *ServerInterfaceWrapper) GetHubInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHubInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSelf operation middleware
func (siw *ServerInterfaceWrapper) RevokeSelf(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSelf(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccessToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAccessToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccessToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGame(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSaveSlot operation middleware
func (siw *ServerInterfaceWrapper) GetSaveSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	// ------------- Path parameter "slot" -------------
	var slot SaveSlotName

	err = runtime.BindStyledParameterWithOptions("simple", "slot", r.PathValue("slot"), &slot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slot", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSaveSlot(w, r, gameId, slot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSave operation middleware
func (siw *ServerInterfaceWrapper) PutSave(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	// ------------- Path parameter "slot" -------------
	var slot SaveSlotName

	err = runtime.BindStyledParameterWithOptions("simple", "slot", r.PathValue("slot"), &slot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slot", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PutSaveParams

	headers := r.Header

	// ------------- Required header parameter "X-FrameBeam-Base-Revision" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-FrameBeam-Base-Revision")]; found {
		var XFrameBeamBaseRevision int
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-FrameBeam-Base-Revision", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-FrameBeam-Base-Revision", valueList[0], &XFrameBeamBaseRevision, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-FrameBeam-Base-Revision", Err: err})
			return
		}

		params.XFrameBeamBaseRevision = XFrameBeamBaseRevision

	} else {
		err := fmt.Errorf("Header parameter X-FrameBeam-Base-Revision is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-FrameBeam-Base-Revision", Err: err})
		return
	}

	// ------------- Required header parameter "X-FrameBeam-Content-SHA256" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-FrameBeam-Content-SHA256")]; found {
		var XFrameBeamContentSHA256 string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-FrameBeam-Content-SHA256", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-FrameBeam-Content-SHA256", valueList[0], &XFrameBeamContentSHA256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-FrameBeam-Content-SHA256", Err: err})
			return
		}

		params.XFrameBeamContentSHA256 = XFrameBeamContentSHA256

	} else {
		err := fmt.Errorf("Header parameter X-FrameBeam-Content-SHA256 is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-FrameBeam-Content-SHA256", Err: err})
		return
	}

	// ------------- Required header parameter "X-FrameBeam-Sync-Reason" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-FrameBeam-Sync-Reason")]; found {
		var XFrameBeamSyncReason SaveSyncReason
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-FrameBeam-Sync-Reason", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-FrameBeam-Sync-Reason", valueList[0], &XFrameBeamSyncReason, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-FrameBeam-Sync-Reason", Err: err})
			return
		}

		params.XFrameBeamSyncReason = XFrameBeamSyncReason

	} else {
		err := fmt.Errorf("Header parameter X-FrameBeam-Sync-Reason is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-FrameBeam-Sync-Reason", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSave(w, r, gameId, slot, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveSaveConflict operation middleware
func (siw *ServerInterfaceWrapper) ResolveSaveConflict(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	// ------------- Path parameter "slot" -------------
	var slot SaveSlotName

	err = runtime.BindStyledParameterWithOptions("simple", "slot", r.PathValue("slot"), &slot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slot", Err: err})
		return
	}

	// ------------- Path parameter "conflict_id" -------------
	var conflictId string

	err = runtime.BindStyledParameterWithOptions("simple", "conflict_id", r.PathValue("conflict_id"), &conflictId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conflict_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveSaveConflict(w, r, gameId, slot, conflictId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadSaveContent operation middleware
func (siw *ServerInterfaceWrapper) DownloadSaveContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	// ------------- Path parameter "slot" -------------
	var slot SaveSlotName

	err = runtime.BindStyledParameterWithOptions("simple", "slot", r.PathValue("slot"), &slot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slot", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSaveContent(w, r, gameId, slot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSaveHistory operation middleware
func (siw *ServerInterfaceWrapper) ListSaveHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	// ------------- Path parameter "slot" -------------
	var slot SaveSlotName

	err = runtime.BindStyledParameterWithOptions("simple", "slot", r.PathValue("slot"), &slot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slot", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSaveHistory(w, r, gameId, slot)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadSaveHistoryContent operation middleware
func (siw *ServerInterfaceWrapper) DownloadSaveHistoryContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId GameId

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	// ------------- Path parameter "slot" -------------
	var slot SaveSlotName

	err = runtime.BindStyledParameterWithOptions("simple", "slot", r.PathValue("slot"), &slot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slot", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version int

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSaveHistoryContent(w, r, gameId, slot, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHandshake operation middleware
func (siw *ServerInterfaceWrapper) PostHandshake(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHandshake(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePairingRequest operation middleware
func (siw *ServerInterfaceWrapper) CreatePairingRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePairingRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPairingRequest operation middleware
func (siw *ServerInterfaceWrapper) GetPairingRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "request_id" -------------
	var requestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", r.PathValue("request_id"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "request_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, PollTokenAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPairingRequest(w, r, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadRom operation middleware
func (siw *ServerInterfaceWrapper) DownloadRom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sha256" -------------
	var sha256 string

	err = runtime.BindStyledParameterWithOptions("simple", "sha256", r.PathValue("sha256"), &sha256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sha256", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadRomParams

	headers := r.Header

	// ------------- Optional header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = &Range

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadRom(w, r, sha256, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSaves operation middleware
func (siw *ServerInterfaceWrapper) ListSaves(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSaves(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectWebSocket operation middleware
func (siw *ServerInterfaceWrapper) ConnectWebSocket(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectWebSocket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/.well-known/framebeam", wrapper.GetHubInfo)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/revoke", wrapper.RevokeSelf)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/token", wrapper.CreateAccessToken)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games", wrapper.ListGames)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games/{game_id}", wrapper.GetGame)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games/{game_id}/saves/{slot}", wrapper.GetSaveSlot)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/games/{game_id}/saves/{slot}", wrapper.PutSave)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/games/{game_id}/saves/{slot}/conflicts/{conflict_id}/resolve", wrapper.ResolveSaveConflict)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games/{game_id}/saves/{slot}/content", wrapper.DownloadSaveContent)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games/{game_id}/saves/{slot}/history", wrapper.ListSaveHistory)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games/{game_id}/saves/{slot}/history/{version}/content", wrapper.DownloadSaveHistoryContent)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/handshake", wrapper.PostHandshake)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/pairing/requests", wrapper.CreatePairingRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/pairing/requests/{request_id}", wrapper.GetPairingRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/roms/{sha256}", wrapper.DownloadRom)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/saves", wrapper.ListSaves)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/ws", wrapper.ConnectWebSocket)

	return m
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedJSONResponse Error

type UnauthorizedJSONResponse Error

type GetHubInfoRequestObject struct {
}

type GetHubInfoResponseObject interface {
	VisitGetHubInfoResponse(w http.ResponseWriter) error
}

type GetHubInfo200JSONResponse HubInfo

func (response GetHubInfo200JSONResponse) VisitGetHubInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RevokeSelfRequestObject struct {
}

type RevokeSelfResponseObject interface {
	VisitRevokeSelfResponse(w http.ResponseWriter) error
}

type RevokeSelf204Response struct {
}

func (response RevokeSelf204Response) VisitRevokeSelfResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeSelf401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeSelf401JSONResponse) VisitRevokeSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccessTokenRequestObject struct {
	Body *CreateAccessTokenJSONRequestBody
}

type CreateAccessTokenResponseObject interface {
	VisitCreateAccessTokenResponse(w http.ResponseWriter) error
}

type CreateAccessToken200JSONResponse TokenResponse

func (response CreateAccessToken200JSONResponse) VisitCreateAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccessToken400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccessToken400JSONResponse) VisitCreateAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccessToken401JSONResponse Error

func (response CreateAccessToken401JSONResponse) VisitCreateAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGamesRequestObject struct {
}

type ListGamesResponseObject interface {
	VisitListGamesResponse(w http.ResponseWriter) error
}

type ListGames200JSONResponse struct {
	Games []Game `json:"games"`
}

func (response ListGames200JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGames401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListGames401JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameRequestObject struct {
	GameId openapi_types.UUID `json:"game_id"`
}

type GetGameResponseObject interface {
	VisitGetGameResponse(w http.ResponseWriter) error
}

type GetGame200JSONResponse Game

func (response GetGame200JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGame401JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGame404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGame404JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSaveSlotRequestObject struct {
	GameId GameId       `json:"game_id"`
	Slot   SaveSlotName `json:"slot"`
}

type GetSaveSlotResponseObject interface {
	VisitGetSaveSlotResponse(w http.ResponseWriter) error
}

type GetSaveSlot200JSONResponse SaveSlot

func (response GetSaveSlot200JSONResponse) VisitGetSaveSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSaveSlot401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSaveSlot401JSONResponse) VisitGetSaveSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSaveSlot403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetSaveSlot403JSONResponse) VisitGetSaveSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSaveSlot404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSaveSlot404JSONResponse) VisitGetSaveSlotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutSaveRequestObject struct {
	GameId GameId       `json:"game_id"`
	Slot   SaveSlotName `json:"slot"`
	Params PutSaveParams
	Body   io.Reader
}

type PutSaveResponseObject interface {
	VisitPutSaveResponse(w http.ResponseWriter) error
}

type PutSave200JSONResponse SaveSlot

func (response PutSave200JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutSave400JSONResponse struct{ BadRequestJSONResponse }

func (response PutSave400JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutSave401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutSave401JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutSave403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutSave403JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutSave404JSONResponse struct{ NotFoundJSONResponse }

func (response PutSave404JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutSave409JSONResponse SaveConflictError

func (response PutSave409JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutSave413JSONResponse Error

func (response PutSave413JSONResponse) VisitPutSaveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSaveConflictRequestObject struct {
	GameId     GameId       `json:"game_id"`
	Slot       SaveSlotName `json:"slot"`
	ConflictId string       `json:"conflict_id"`
	Body       *ResolveSaveConflictJSONRequestBody
}

type ResolveSaveConflictResponseObject interface {
	VisitResolveSaveConflictResponse(w http.ResponseWriter) error
}

type ResolveSaveConflict200JSONResponse SaveSlot

func (response ResolveSaveConflict200JSONResponse) VisitResolveSaveConflictResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSaveConflict400JSONResponse struct{ BadRequestJSONResponse }

func (response ResolveSaveConflict400JSONResponse) VisitResolveSaveConflictResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSaveConflict401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ResolveSaveConflict401JSONResponse) VisitResolveSaveConflictResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSaveConflict403JSONResponse struct{ ForbiddenJSONResponse }

func (response ResolveSaveConflict403JSONResponse) VisitResolveSaveConflictResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSaveConflict404JSONResponse struct{ NotFoundJSONResponse }

func (response ResolveSaveConflict404JSONResponse) VisitResolveSaveConflictResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResolveSaveConflict409JSONResponse Error

func (response ResolveSaveConflict409JSONResponse) VisitResolveSaveConflictResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSaveContentRequestObject struct {
	GameId GameId       `json:"game_id"`
	Slot   SaveSlotName `json:"slot"`
}

type DownloadSaveContentResponseObject interface {
	VisitDownloadSaveContentResponse(w http.ResponseWriter) error
}

type DownloadSaveContent200ResponseHeaders struct {
	ContentLength          int64
	ETag                   string
	XFrameBeamSaveRevision int
}

type DownloadSaveContent200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadSaveContent200ResponseHeaders
	ContentLength int64
}

func (response DownloadSaveContent200ApplicationoctetStreamResponse) VisitDownloadSaveContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("X-FrameBeam-Save-Revision", fmt.Sprint(response.Headers.XFrameBeamSaveRevision))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadSaveContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DownloadSaveContent401JSONResponse) VisitDownloadSaveContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSaveContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response DownloadSaveContent403JSONResponse) VisitDownloadSaveContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSaveContent404JSONResponse struct{ NotFoundJSONResponse }

func (response DownloadSaveContent404JSONResponse) VisitDownloadSaveContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListSaveHistoryRequestObject struct {
	GameId GameId       `json:"game_id"`
	Slot   SaveSlotName `json:"slot"`
}

type ListSaveHistoryResponseObject interface {
	VisitListSaveHistoryResponse(w http.ResponseWriter) error
}

type ListSaveHistory200JSONResponse struct {
	Versions []SaveHistoryVersion `json:"versions"`
}

func (response ListSaveHistory200JSONResponse) VisitListSaveHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSaveHistory401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSaveHistory401JSONResponse) VisitListSaveHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListSaveHistory403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListSaveHistory403JSONResponse) VisitListSaveHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListSaveHistory404JSONResponse struct{ NotFoundJSONResponse }

func (response ListSaveHistory404JSONResponse) VisitListSaveHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSaveHistoryContentRequestObject struct {
	GameId  GameId       `json:"game_id"`
	Slot    SaveSlotName `json:"slot"`
	Version int          `json:"version"`
}

type DownloadSaveHistoryContentResponseObject interface {
	VisitDownloadSaveHistoryContentResponse(w http.ResponseWriter) error
}

type DownloadSaveHistoryContent200ResponseHeaders struct {
	ContentLength          int64
	ETag                   string
	XFrameBeamSaveRevision int
}

type DownloadSaveHistoryContent200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadSaveHistoryContent200ResponseHeaders
	ContentLength int64
}

func (response DownloadSaveHistoryContent200ApplicationoctetStreamResponse) VisitDownloadSaveHistoryContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("X-FrameBeam-Save-Revision", fmt.Sprint(response.Headers.XFrameBeamSaveRevision))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadSaveHistoryContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DownloadSaveHistoryContent401JSONResponse) VisitDownloadSaveHistoryContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSaveHistoryContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response DownloadSaveHistoryContent403JSONResponse) VisitDownloadSaveHistoryContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DownloadSaveHistoryContent404JSONResponse struct{ NotFoundJSONResponse }

func (response DownloadSaveHistoryContent404JSONResponse) VisitDownloadSaveHistoryContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostHandshakeRequestObject struct {
	Body *PostHandshakeJSONRequestBody
}

type PostHandshakeResponseObject interface {
	VisitPostHandshakeResponse(w http.ResponseWriter) error
}

type PostHandshake200JSONResponse HandshakeResponse

func (response PostHandshake200JSONResponse) VisitPostHandshakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostHandshake400JSONResponse struct{ BadRequestJSONResponse }

func (response PostHandshake400JSONResponse) VisitPostHandshakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostHandshake401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostHandshake401JSONResponse) VisitPostHandshakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreatePairingRequestRequestObject struct {
	Body *CreatePairingRequestJSONRequestBody
}

type CreatePairingRequestResponseObject interface {
	VisitCreatePairingRequestResponse(w http.ResponseWriter) error
}

type CreatePairingRequest202JSONResponse PairingRequestAccepted

func (response CreatePairingRequest202JSONResponse) VisitCreatePairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreatePairingRequest400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePairingRequest400JSONResponse) VisitCreatePairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePairingRequest429JSONResponse struct{ RateLimitedJSONResponse }

func (response CreatePairingRequest429JSONResponse) VisitCreatePairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetPairingRequestRequestObject struct {
	RequestId openapi_types.UUID `json:"request_id"`
}

type GetPairingRequestResponseObject interface {
	VisitGetPairingRequestResponse(w http.ResponseWriter) error
}

type GetPairingRequest200JSONResponse PairingStatus

func (response GetPairingRequest200JSONResponse) VisitGetPairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPairingRequest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPairingRequest401JSONResponse) VisitGetPairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPairingRequest404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPairingRequest404JSONResponse) VisitGetPairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadRomRequestObject struct {
	Sha256 string `json:"sha256"`
	Params DownloadRomParams
}

type DownloadRomResponseObject interface {
	VisitDownloadRomResponse(w http.ResponseWriter) error
}

type DownloadRom200ResponseHeaders struct {
	AcceptRanges  string
	ContentLength int64
	ETag          string
}

type DownloadRom200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadRom200ResponseHeaders
	ContentLength int64
}

func (response DownloadRom200ApplicationoctetStreamResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Accept-Ranges", fmt.Sprint(response.Headers.AcceptRanges))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadRom206ResponseHeaders struct {
	ContentLength int64
	ContentRange  string
	ETag          string
}

type DownloadRom206ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadRom206ResponseHeaders
	ContentLength int64
}

func (response DownloadRom206ApplicationoctetStreamResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Range", fmt.Sprint(response.Headers.ContentRange))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(206)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadRom401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DownloadRom401JSONResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DownloadRom404JSONResponse struct{ NotFoundJSONResponse }

func (response DownloadRom404JSONResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadRom416JSONResponse Error

func (response DownloadRom416JSONResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(416)

	return json.NewEncoder(w).Encode(response)
}

type ListSavesRequestObject struct {
}

type ListSavesResponseObject interface {
	VisitListSavesResponse(w http.ResponseWriter) error
}

type ListSaves200JSONResponse struct {
	Saves []SaveSlotSummary `json:"saves"`
}

func (response ListSaves200JSONResponse) VisitListSavesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSaves401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSaves401JSONResponse) VisitListSavesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ConnectWebSocketRequestObject struct {
}

type ConnectWebSocketResponseObject interface {
	VisitConnectWebSocketResponse(w http.ResponseWriter) error
}

type ConnectWebSocket101Response struct {
}

func (response ConnectWebSocket101Response) VisitConnectWebSocketResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type ConnectWebSocket401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ConnectWebSocket401JSONResponse) VisitConnectWebSocketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Hub info (no auth, grants no rights)
	// (GET /.well-known/framebeam)
	GetHubInfo(ctx context.Context, request GetHubInfoRequestObject) (GetHubInfoResponseObject, error)
	// Device revokes itself
	// (POST /api/v1/auth/revoke)
	RevokeSelf(ctx context.Context, request RevokeSelfRequestObject) (RevokeSelfResponseObject, error)
	// Exchange device credential for access token
	// (POST /api/v1/auth/token)
	CreateAccessToken(ctx context.Context, request CreateAccessTokenRequestObject) (CreateAccessTokenResponseObject, error)
	// Game library
	// (GET /api/v1/games)
	ListGames(ctx context.Context, request ListGamesRequestObject) (ListGamesResponseObject, error)
	// Single game
	// (GET /api/v1/games/{game_id})
	GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error)
	// Current checkpoint metadata and open conflicts of a slot
	// (GET /api/v1/games/{game_id}/saves/{slot})
	GetSaveSlot(ctx context.Context, request GetSaveSlotRequestObject) (GetSaveSlotResponseObject, error)
	// Upload the save file (raw body) against a base revision
	// (PUT /api/v1/games/{game_id}/saves/{slot})
	PutSave(ctx context.Context, request PutSaveRequestObject) (PutSaveResponseObject, error)
	// Resolve an open save conflict
	// (POST /api/v1/games/{game_id}/saves/{slot}/conflicts/{conflict_id}/resolve)
	ResolveSaveConflict(ctx context.Context, request ResolveSaveConflictRequestObject) (ResolveSaveConflictResponseObject, error)
	// Bytes of the current checkpoint
	// (GET /api/v1/games/{game_id}/saves/{slot}/content)
	DownloadSaveContent(ctx context.Context, request DownloadSaveContentRequestObject) (DownloadSaveContentResponseObject, error)
	// Permanent history versions of a slot (newest first)
	// (GET /api/v1/games/{game_id}/saves/{slot}/history)
	ListSaveHistory(ctx context.Context, request ListSaveHistoryRequestObject) (ListSaveHistoryResponseObject, error)
	// Bytes of a history version
	// (GET /api/v1/games/{game_id}/saves/{slot}/history/{version}/content)
	DownloadSaveHistoryContent(ctx context.Context, request DownloadSaveHistoryContentRequestObject) (DownloadSaveHistoryContentResponseObject, error)
	// Handshake with capability negotiation
	// (POST /api/v1/handshake)
	PostHandshake(ctx context.Context, request PostHandshakeRequestObject) (PostHandshakeResponseObject, error)
	// Submit pairing request (admin decides allow/deny)
	// (POST /api/v1/pairing/requests)
	CreatePairingRequest(ctx context.Context, request CreatePairingRequestRequestObject) (CreatePairingRequestResponseObject, error)
	// Poll pairing request status (bearer = poll_token)
	// (GET /api/v1/pairing/requests/{request_id})
	GetPairingRequest(ctx context.Context, request GetPairingRequestRequestObject) (GetPairingRequestResponseObject, error)
	// ROM download (range support). Upload only via the admin web interface.
	// (GET /api/v1/roms/{sha256})
	DownloadRom(ctx context.Context, request DownloadRomRequestObject) (DownloadRomResponseObject, error)
	// Save slots of the authenticated device's user
	// (GET /api/v1/saves)
	ListSaves(ctx context.Context, request ListSavesRequestObject) (ListSavesResponseObject, error)
	// WSS upgrade (documentation only, implementation to follow)
	// (GET /api/v1/ws)
	ConnectWebSocket(ctx context.Context, request ConnectWebSocketRequestObject) (ConnectWebSocketResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHubInfo operation middleware
func (sh *strictHandler) GetHubInfo(w http.ResponseWriter, r *http.Request) {
	var request GetHubInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHubInfo(ctx, request.(GetHubInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHubInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHubInfoResponseObject); ok {
		if err := validResponse.VisitGetHubInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeSelf operation middleware
func (sh *strictHandler) RevokeSelf(w http.ResponseWriter, r *http.Request) {
	var request RevokeSelfRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeSelf(ctx, request.(RevokeSelfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeSelf")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeSelfResponseObject); ok {
		if err := validResponse.VisitRevokeSelfResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccessToken operation middleware
func (sh *strictHandler) CreateAccessToken(w http.ResponseWriter, r *http.Request) {
	var request CreateAccessTokenRequestObject

	var body CreateAccessTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccessToken(ctx, request.(CreateAccessTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccessToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccessTokenResponseObject); ok {
		if err := validResponse.VisitCreateAccessTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGames operation middleware
func (sh *strictHandler) ListGames(w http.ResponseWriter, r *http.Request) {
	var request ListGamesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGames(ctx, request.(ListGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGamesResponseObject); ok {
		if err := validResponse.VisitListGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGame operation middleware
func (sh *strictHandler) GetGame(w http.ResponseWriter, r *http.Request, gameId openapi_types.UUID) {
	var request GetGameRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGame(ctx, request.(GetGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameResponseObject); ok {
		if err := validResponse.VisitGetGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSaveSlot operation middleware
func (sh *strictHandler) GetSaveSlot(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName) {
	var request GetSaveSlotRequestObject

	request.GameId = gameId
	request.Slot = slot

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSaveSlot(ctx, request.(GetSaveSlotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSaveSlot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSaveSlotResponseObject); ok {
		if err := validResponse.VisitGetSaveSlotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutSave operation middleware
func (sh *strictHandler) PutSave(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName, params PutSaveParams) {
	var request PutSaveRequestObject

	request.GameId = gameId
	request.Slot = slot
	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutSave(ctx, request.(PutSaveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutSave")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutSaveResponseObject); ok {
		if err := validResponse.VisitPutSaveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResolveSaveConflict operation middleware
func (sh *strictHandler) ResolveSaveConflict(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName, conflictId string) {
	var request ResolveSaveConflictRequestObject

	request.GameId = gameId
	request.Slot = slot
	request.ConflictId = conflictId

	var body ResolveSaveConflictJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveSaveConflict(ctx, request.(ResolveSaveConflictRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveSaveConflict")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveSaveConflictResponseObject); ok {
		if err := validResponse.VisitResolveSaveConflictResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadSaveContent operation middleware
func (sh *strictHandler) DownloadSaveContent(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName) {
	var request DownloadSaveContentRequestObject

	request.GameId = gameId
	request.Slot = slot

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSaveContent(ctx, request.(DownloadSaveContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSaveContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSaveContentResponseObject); ok {
		if err := validResponse.VisitDownloadSaveContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSaveHistory operation middleware
func (sh *strictHandler) ListSaveHistory(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName) {
	var request ListSaveHistoryRequestObject

	request.GameId = gameId
	request.Slot = slot

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSaveHistory(ctx, request.(ListSaveHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSaveHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSaveHistoryResponseObject); ok {
		if err := validResponse.VisitListSaveHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadSaveHistoryContent operation middleware
func (sh *strictHandler) DownloadSaveHistoryContent(w http.ResponseWriter, r *http.Request, gameId GameId, slot SaveSlotName, version int) {
	var request DownloadSaveHistoryContentRequestObject

	request.GameId = gameId
	request.Slot = slot
	request.Version = version

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSaveHistoryContent(ctx, request.(DownloadSaveHistoryContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSaveHistoryContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSaveHistoryContentResponseObject); ok {
		if err := validResponse.VisitDownloadSaveHistoryContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostHandshake operation middleware
func (sh *strictHandler) PostHandshake(w http.ResponseWriter, r *http.Request) {
	var request PostHandshakeRequestObject

	var body PostHandshakeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostHandshake(ctx, request.(PostHandshakeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostHandshake")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostHandshakeResponseObject); ok {
		if err := validResponse.VisitPostHandshakeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePairingRequest operation middleware
func (sh *strictHandler) CreatePairingRequest(w http.ResponseWriter, r *http.Request) {
	var request CreatePairingRequestRequestObject

	var body CreatePairingRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePairingRequest(ctx, request.(CreatePairingRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePairingRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePairingRequestResponseObject); ok {
		if err := validResponse.VisitCreatePairingRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPairingRequest operation middleware
func (sh *strictHandler) GetPairingRequest(w http.ResponseWriter, r *http.Request, requestId openapi_types.UUID) {
	var request GetPairingRequestRequestObject

	request.RequestId = requestId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPairingRequest(ctx, request.(GetPairingRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPairingRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPairingRequestResponseObject); ok {
		if err := validResponse.VisitGetPairingRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadRom operation middleware
func (sh *strictHandler) DownloadRom(w http.ResponseWriter, r *http.Request, sha256 string, params DownloadRomParams) {
	var request DownloadRomRequestObject

	request.Sha256 = sha256
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadRom(ctx, request.(DownloadRomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadRom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadRomResponseObject); ok {
		if err := validResponse.VisitDownloadRomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSaves operation middleware
func (sh *strictHandler) ListSaves(w http.ResponseWriter, r *http.Request) {
	var request ListSavesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSaves(ctx, request.(ListSavesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSaves")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSavesResponseObject); ok {
		if err := validResponse.VisitListSavesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConnectWebSocket operation middleware
func (sh *strictHandler) ConnectWebSocket(w http.ResponseWriter, r *http.Request) {
	var request ConnectWebSocketRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConnectWebSocket(ctx, request.(ConnectWebSocketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConnectWebSocket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConnectWebSocketResponseObject); ok {
		if err := validResponse.VisitConnectWebSocketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
