//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    = "bearerAuth.Scopes"
	PollTokenAuthScopes = "pollTokenAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeBadRequest          ErrorCode = "bad_request"
	ErrorCodeCapabilityMissing   ErrorCode = "capability_missing"
	ErrorCodeConflict            ErrorCode = "conflict"
	ErrorCodeCoreMissing         ErrorCode = "core_missing"
	ErrorCodeCoreVersionMismatch ErrorCode = "core_version_mismatch"
	ErrorCodeDeviceRevoked       ErrorCode = "device_revoked"
	ErrorCodeForbidden           ErrorCode = "forbidden"
	ErrorCodeHubTooOld           ErrorCode = "hub_too_old"
	ErrorCodeInternal            ErrorCode = "internal"
	ErrorCodeInvalidCredentials  ErrorCode = "invalid_credentials"
	ErrorCodeNotFound            ErrorCode = "not_found"
	ErrorCodePairingDenied       ErrorCode = "pairing_denied"
	ErrorCodePairingExpired      ErrorCode = "pairing_expired"
	ErrorCodePairingPending      ErrorCode = "pairing_pending"
	ErrorCodePlayerTooOld        ErrorCode = "player_too_old"
	ErrorCodeRateLimited         ErrorCode = "rate_limited"
	ErrorCodeUnauthorized        ErrorCode = "unauthorized"
)

// Defines values for HandshakeProblemCode.
const (
	HandshakeProblemCodeCapabilityMissing   HandshakeProblemCode = "capability_missing"
	HandshakeProblemCodeCoreMissing         HandshakeProblemCode = "core_missing"
	HandshakeProblemCodeCoreVersionMismatch HandshakeProblemCode = "core_version_mismatch"
	HandshakeProblemCodeHubTooOld           HandshakeProblemCode = "hub_too_old"
	HandshakeProblemCodePlayerTooOld        HandshakeProblemCode = "player_too_old"
)

// Defines values for PairingRequestAcceptedStatus.
const (
	PairingRequestAcceptedStatusPending PairingRequestAcceptedStatus = "pending"
)

// Defines values for PairingStatusStatus.
const (
	PairingStatusStatusApproved PairingStatusStatus = "approved"
	PairingStatusStatusDenied   PairingStatusStatus = "denied"
	PairingStatusStatusExpired  PairingStatusStatus = "expired"
	PairingStatusStatusPending  PairingStatusStatus = "pending"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// CoreInfo defines model for CoreInfo.
type CoreInfo struct {
	Id      string `json:"id"`
	Version string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Game defines model for Game.
type Game struct {
	AddedAt time.Time          `json:"added_at"`
	Id      openapi_types.UUID `json:"id"`
	Rom     RomInfo            `json:"rom"`
	System  string             `json:"system"`
	Title   string             `json:"title"`

	// UploadedBy Hub-lokale User-ID
	UploadedBy string `json:"uploaded_by"`
}

// HandshakeProblem defines model for HandshakeProblem.
type HandshakeProblem struct {
	Code   HandshakeProblemCode `json:"code"`
	CoreId *string              `json:"core_id,omitempty"`
	Detail string               `json:"detail"`
}

// HandshakeProblemCode defines model for HandshakeProblem.Code.
type HandshakeProblemCode string

// HandshakeRequest defines model for HandshakeRequest.
type HandshakeRequest struct {
	Arch                 string                 `json:"arch"`
	Audio                HandshakeRequest_Audio `json:"audio"`
	Cores                []CoreInfo             `json:"cores"`
	Input                HandshakeRequest_Input `json:"input"`
	MinProtocolVersion   int                    `json:"min_protocol_version"`
	Platform             string                 `json:"platform"`
	PlayerVersion        string                 `json:"player_version"`
	ProtocolVersion      int                    `json:"protocol_version"`
	Video                HandshakeRequest_Video `json:"video"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeRequest_Audio defines model for HandshakeRequest.Audio.
type HandshakeRequest_Audio struct {
	Opus                 bool                   `json:"opus"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeRequest_Input defines model for HandshakeRequest.Input.
type HandshakeRequest_Input struct {
	Gamepad              bool                   `json:"gamepad"`
	Keyboard             bool                   `json:"keyboard"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeRequest_Video defines model for HandshakeRequest.Video.
type HandshakeRequest_Video struct {
	Encoders             []string               `json:"encoders"`
	H264Decode           bool                   `json:"h264_decode"`
	H264Encode           bool                   `json:"h264_encode"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HandshakeResponse defines model for HandshakeResponse.
type HandshakeResponse struct {
	Compatible         bool               `json:"compatible"`
	HubVersion         string             `json:"hub_version"`
	MinProtocolVersion int                `json:"min_protocol_version"`
	Problems           []HandshakeProblem `json:"problems"`
	ProtocolVersion    int                `json:"protocol_version"`
}

// HubInfo defines model for HubInfo.
type HubInfo struct {
	ApiBase            string             `json:"api_base"`
	HubId              openapi_types.UUID `json:"hub_id"`
	HubVersion         string             `json:"hub_version"`
	MinProtocolVersion int                `json:"min_protocol_version"`
	Name               string             `json:"name"`
	ProtocolVersion    int                `json:"protocol_version"`
}

// PairingRequestAccepted defines model for PairingRequestAccepted.
type PairingRequestAccepted struct {
	// ExpiresIn Sekunden
	ExpiresIn int `json:"expires_in"`

	// PollToken Präfix fbp_
	PollToken string                       `json:"poll_token"`
	RequestId openapi_types.UUID           `json:"request_id"`
	Status    PairingRequestAcceptedStatus `json:"status"`
}

// PairingRequestAcceptedStatus defines model for PairingRequestAccepted.Status.
type PairingRequestAcceptedStatus string

// PairingRequestCreate defines model for PairingRequestCreate.
type PairingRequestCreate struct {
	Arch            string             `json:"arch"`
	DeviceId        openapi_types.UUID `json:"device_id"`
	DeviceName      string             `json:"device_name"`
	Platform        string             `json:"platform"`
	PlayerVersion   string             `json:"player_version"`
	ProtocolVersion int                `json:"protocol_version"`
}

// PairingStatus defines model for PairingStatus.
type PairingStatus struct {
	// DeviceCredential Präfix fbd_; nur bei approved, einmalig
	DeviceCredential *string `json:"device_credential,omitempty"`

	// HubId Nur bei approved (einmalig)
	HubId  *openapi_types.UUID `json:"hub_id,omitempty"`
	Status PairingStatusStatus `json:"status"`

	// UserId Hub-lokale User-ID; nur bei approved
	UserId *string `json:"user_id,omitempty"`
}

// PairingStatusStatus defines model for PairingStatus.Status.
type PairingStatusStatus string

// RomInfo defines model for RomInfo.
type RomInfo struct {
	Filename string `json:"filename"`
	Sha256   string `json:"sha256"`
	Size     int64  `json:"size"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	DeviceCredential string             `json:"device_credential"`
	DeviceId         openapi_types.UUID `json:"device_id"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Präfix fba_
	AccessToken string `json:"access_token"`

	// ExpiresIn Sekunden
	ExpiresIn int                    `json:"expires_in"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// DownloadRomParams defines parameters for DownloadRom.
type DownloadRomParams struct {
	Range *string `json:"Range,omitempty"`
}

// CreateAccessTokenJSONRequestBody defines body for CreateAccessToken for application/json ContentType.
type CreateAccessTokenJSONRequestBody = TokenRequest

// PostHandshakeJSONRequestBody defines body for PostHandshake for application/json ContentType.
type PostHandshakeJSONRequestBody = HandshakeRequest

// CreatePairingRequestJSONRequestBody defines body for CreatePairingRequest for application/json ContentType.
type CreatePairingRequestJSONRequestBody = PairingRequestCreate

// Getter for additional properties for HandshakeRequest. Returns the specified
// element and whether it was found
func (a HandshakeRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest
func (a *HandshakeRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest to handle AdditionalProperties
func (a *HandshakeRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["arch"]; found {
		err = json.Unmarshal(raw, &a.Arch)
		if err != nil {
			return fmt.Errorf("error reading 'arch': %w", err)
		}
		delete(object, "arch")
	}

	if raw, found := object["audio"]; found {
		err = json.Unmarshal(raw, &a.Audio)
		if err != nil {
			return fmt.Errorf("error reading 'audio': %w", err)
		}
		delete(object, "audio")
	}

	if raw, found := object["cores"]; found {
		err = json.Unmarshal(raw, &a.Cores)
		if err != nil {
			return fmt.Errorf("error reading 'cores': %w", err)
		}
		delete(object, "cores")
	}

	if raw, found := object["input"]; found {
		err = json.Unmarshal(raw, &a.Input)
		if err != nil {
			return fmt.Errorf("error reading 'input': %w", err)
		}
		delete(object, "input")
	}

	if raw, found := object["min_protocol_version"]; found {
		err = json.Unmarshal(raw, &a.MinProtocolVersion)
		if err != nil {
			return fmt.Errorf("error reading 'min_protocol_version': %w", err)
		}
		delete(object, "min_protocol_version")
	}

	if raw, found := object["platform"]; found {
		err = json.Unmarshal(raw, &a.Platform)
		if err != nil {
			return fmt.Errorf("error reading 'platform': %w", err)
		}
		delete(object, "platform")
	}

	if raw, found := object["player_version"]; found {
		err = json.Unmarshal(raw, &a.PlayerVersion)
		if err != nil {
			return fmt.Errorf("error reading 'player_version': %w", err)
		}
		delete(object, "player_version")
	}

	if raw, found := object["protocol_version"]; found {
		err = json.Unmarshal(raw, &a.ProtocolVersion)
		if err != nil {
			return fmt.Errorf("error reading 'protocol_version': %w", err)
		}
		delete(object, "protocol_version")
	}

	if raw, found := object["video"]; found {
		err = json.Unmarshal(raw, &a.Video)
		if err != nil {
			return fmt.Errorf("error reading 'video': %w", err)
		}
		delete(object, "video")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest to handle AdditionalProperties
func (a HandshakeRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["arch"], err = json.Marshal(a.Arch)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'arch': %w", err)
	}

	object["audio"], err = json.Marshal(a.Audio)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'audio': %w", err)
	}

	if a.Cores != nil {
		object["cores"], err = json.Marshal(a.Cores)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cores': %w", err)
		}
	}

	object["input"], err = json.Marshal(a.Input)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'input': %w", err)
	}

	object["min_protocol_version"], err = json.Marshal(a.MinProtocolVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min_protocol_version': %w", err)
	}

	object["platform"], err = json.Marshal(a.Platform)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'platform': %w", err)
	}

	object["player_version"], err = json.Marshal(a.PlayerVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'player_version': %w", err)
	}

	object["protocol_version"], err = json.Marshal(a.ProtocolVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'protocol_version': %w", err)
	}

	object["video"], err = json.Marshal(a.Video)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'video': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HandshakeRequest_Audio. Returns the specified
// element and whether it was found
func (a HandshakeRequest_Audio) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest_Audio
func (a *HandshakeRequest_Audio) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest_Audio to handle AdditionalProperties
func (a *HandshakeRequest_Audio) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["opus"]; found {
		err = json.Unmarshal(raw, &a.Opus)
		if err != nil {
			return fmt.Errorf("error reading 'opus': %w", err)
		}
		delete(object, "opus")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest_Audio to handle AdditionalProperties
func (a HandshakeRequest_Audio) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["opus"], err = json.Marshal(a.Opus)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'opus': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HandshakeRequest_Input. Returns the specified
// element and whether it was found
func (a HandshakeRequest_Input) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest_Input
func (a *HandshakeRequest_Input) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest_Input to handle AdditionalProperties
func (a *HandshakeRequest_Input) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["gamepad"]; found {
		err = json.Unmarshal(raw, &a.Gamepad)
		if err != nil {
			return fmt.Errorf("error reading 'gamepad': %w", err)
		}
		delete(object, "gamepad")
	}

	if raw, found := object["keyboard"]; found {
		err = json.Unmarshal(raw, &a.Keyboard)
		if err != nil {
			return fmt.Errorf("error reading 'keyboard': %w", err)
		}
		delete(object, "keyboard")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest_Input to handle AdditionalProperties
func (a HandshakeRequest_Input) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["gamepad"], err = json.Marshal(a.Gamepad)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'gamepad': %w", err)
	}

	object["keyboard"], err = json.Marshal(a.Keyboard)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'keyboard': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HandshakeRequest_Video. Returns the specified
// element and whether it was found
func (a HandshakeRequest_Video) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HandshakeRequest_Video
func (a *HandshakeRequest_Video) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HandshakeRequest_Video to handle AdditionalProperties
func (a *HandshakeRequest_Video) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["encoders"]; found {
		err = json.Unmarshal(raw, &a.Encoders)
		if err != nil {
			return fmt.Errorf("error reading 'encoders': %w", err)
		}
		delete(object, "encoders")
	}

	if raw, found := object["h264_decode"]; found {
		err = json.Unmarshal(raw, &a.H264Decode)
		if err != nil {
			return fmt.Errorf("error reading 'h264_decode': %w", err)
		}
		delete(object, "h264_decode")
	}

	if raw, found := object["h264_encode"]; found {
		err = json.Unmarshal(raw, &a.H264Encode)
		if err != nil {
			return fmt.Errorf("error reading 'h264_encode': %w", err)
		}
		delete(object, "h264_encode")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HandshakeRequest_Video to handle AdditionalProperties
func (a HandshakeRequest_Video) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Encoders != nil {
		object["encoders"], err = json.Marshal(a.Encoders)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'encoders': %w", err)
		}
	}

	object["h264_decode"], err = json.Marshal(a.H264Decode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'h264_decode': %w", err)
	}

	object["h264_encode"], err = json.Marshal(a.H264Encode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'h264_encode': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Hub-Info (ohne Auth, verleiht keine Rechte)
	// (GET /.well-known/framebeam)
	GetHubInfo(w http.ResponseWriter, r *http.Request)
	// Gerät widerruft sich selbst
	// (POST /api/v1/auth/revoke)
	RevokeSelf(w http.ResponseWriter, r *http.Request)
	// Access Token gegen Device Credential tauschen
	// (POST /api/v1/auth/token)
	CreateAccessToken(w http.ResponseWriter, r *http.Request)
	// Spielebibliothek
	// (GET /api/v1/games)
	ListGames(w http.ResponseWriter, r *http.Request)
	// Einzelnes Spiel
	// (GET /api/v1/games/{game_id})
	GetGame(w http.ResponseWriter, r *http.Request, gameId openapi_types.UUID)
	// Handshake mit Capability Negotiation
	// (POST /api/v1/handshake)
	PostHandshake(w http.ResponseWriter, r *http.Request)
	// Pairing-Anfrage stellen (Admin entscheidet Allow/Deny)
	// (POST /api/v1/pairing/requests)
	CreatePairingRequest(w http.ResponseWriter, r *http.Request)
	// Status der Pairing-Anfrage abfragen (Bearer = poll_token)
	// (GET /api/v1/pairing/requests/{request_id})
	GetPairingRequest(w http.ResponseWriter, r *http.Request, requestId openapi_types.UUID)
	// ROM-Download (Range-Unterstützung). Upload nur über das Admin-Webinterface.
	// (GET /api/v1/roms/{sha256})
	DownloadRom(w http.ResponseWriter, r *http.Request, sha256 string, params DownloadRomParams)
	// WSS-Upgrade (nur Dokumentation, Implementierung folgt)
	// (GET /api/v1/ws)
	ConnectWebSocket(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHubInfo operation middleware
func (siw *ServerInterfaceWrapper) GetHubInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHubInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSelf operation middleware
func (siw *ServerInterfaceWrapper) RevokeSelf(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSelf(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccessToken operation middleware
func (siw *ServerInterfaceWrapper) CreateAccessToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccessToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", r.PathValue("game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGame(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHandshake operation middleware
func (siw *ServerInterfaceWrapper) PostHandshake(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHandshake(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePairingRequest operation middleware
func (siw *ServerInterfaceWrapper) CreatePairingRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePairingRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPairingRequest operation middleware
func (siw *ServerInterfaceWrapper) GetPairingRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "request_id" -------------
	var requestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", r.PathValue("request_id"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "request_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, PollTokenAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPairingRequest(w, r, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadRom operation middleware
func (siw *ServerInterfaceWrapper) DownloadRom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sha256" -------------
	var sha256 string

	err = runtime.BindStyledParameterWithOptions("simple", "sha256", r.PathValue("sha256"), &sha256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sha256", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadRomParams

	headers := r.Header

	// ------------- Optional header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = &Range

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadRom(w, r, sha256, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectWebSocket operation middleware
func (siw *ServerInterfaceWrapper) ConnectWebSocket(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectWebSocket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/.well-known/framebeam", wrapper.GetHubInfo)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/revoke", wrapper.RevokeSelf)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/token", wrapper.CreateAccessToken)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games", wrapper.ListGames)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/games/{game_id}", wrapper.GetGame)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/handshake", wrapper.PostHandshake)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/pairing/requests", wrapper.CreatePairingRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/pairing/requests/{request_id}", wrapper.GetPairingRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/roms/{sha256}", wrapper.DownloadRom)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/ws", wrapper.ConnectWebSocket)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedJSONResponse Error

type UnauthorizedJSONResponse Error

type GetHubInfoRequestObject struct {
}

type GetHubInfoResponseObject interface {
	VisitGetHubInfoResponse(w http.ResponseWriter) error
}

type GetHubInfo200JSONResponse HubInfo

func (response GetHubInfo200JSONResponse) VisitGetHubInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RevokeSelfRequestObject struct {
}

type RevokeSelfResponseObject interface {
	VisitRevokeSelfResponse(w http.ResponseWriter) error
}

type RevokeSelf204Response struct {
}

func (response RevokeSelf204Response) VisitRevokeSelfResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeSelf401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeSelf401JSONResponse) VisitRevokeSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccessTokenRequestObject struct {
	Body *CreateAccessTokenJSONRequestBody
}

type CreateAccessTokenResponseObject interface {
	VisitCreateAccessTokenResponse(w http.ResponseWriter) error
}

type CreateAccessToken200JSONResponse TokenResponse

func (response CreateAccessToken200JSONResponse) VisitCreateAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccessToken400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccessToken400JSONResponse) VisitCreateAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccessToken401JSONResponse Error

func (response CreateAccessToken401JSONResponse) VisitCreateAccessTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGamesRequestObject struct {
}

type ListGamesResponseObject interface {
	VisitListGamesResponse(w http.ResponseWriter) error
}

type ListGames200JSONResponse struct {
	Games []Game `json:"games"`
}

func (response ListGames200JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGames401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListGames401JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameRequestObject struct {
	GameId openapi_types.UUID `json:"game_id"`
}

type GetGameResponseObject interface {
	VisitGetGameResponse(w http.ResponseWriter) error
}

type GetGame200JSONResponse Game

func (response GetGame200JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGame401JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGame404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGame404JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostHandshakeRequestObject struct {
	Body *PostHandshakeJSONRequestBody
}

type PostHandshakeResponseObject interface {
	VisitPostHandshakeResponse(w http.ResponseWriter) error
}

type PostHandshake200JSONResponse HandshakeResponse

func (response PostHandshake200JSONResponse) VisitPostHandshakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostHandshake400JSONResponse struct{ BadRequestJSONResponse }

func (response PostHandshake400JSONResponse) VisitPostHandshakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostHandshake401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostHandshake401JSONResponse) VisitPostHandshakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreatePairingRequestRequestObject struct {
	Body *CreatePairingRequestJSONRequestBody
}

type CreatePairingRequestResponseObject interface {
	VisitCreatePairingRequestResponse(w http.ResponseWriter) error
}

type CreatePairingRequest202JSONResponse PairingRequestAccepted

func (response CreatePairingRequest202JSONResponse) VisitCreatePairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CreatePairingRequest400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePairingRequest400JSONResponse) VisitCreatePairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePairingRequest429JSONResponse struct{ RateLimitedJSONResponse }

func (response CreatePairingRequest429JSONResponse) VisitCreatePairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetPairingRequestRequestObject struct {
	RequestId openapi_types.UUID `json:"request_id"`
}

type GetPairingRequestResponseObject interface {
	VisitGetPairingRequestResponse(w http.ResponseWriter) error
}

type GetPairingRequest200JSONResponse PairingStatus

func (response GetPairingRequest200JSONResponse) VisitGetPairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPairingRequest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPairingRequest401JSONResponse) VisitGetPairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPairingRequest404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPairingRequest404JSONResponse) VisitGetPairingRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadRomRequestObject struct {
	Sha256 string `json:"sha256"`
	Params DownloadRomParams
}

type DownloadRomResponseObject interface {
	VisitDownloadRomResponse(w http.ResponseWriter) error
}

type DownloadRom200ResponseHeaders struct {
	AcceptRanges  string
	ContentLength int64
	ETag          string
}

type DownloadRom200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadRom200ResponseHeaders
	ContentLength int64
}

func (response DownloadRom200ApplicationoctetStreamResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Accept-Ranges", fmt.Sprint(response.Headers.AcceptRanges))
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadRom206ResponseHeaders struct {
	ContentLength int64
	ContentRange  string
	ETag          string
}

type DownloadRom206ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadRom206ResponseHeaders
	ContentLength int64
}

func (response DownloadRom206ApplicationoctetStreamResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Range", fmt.Sprint(response.Headers.ContentRange))
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.WriteHeader(206)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadRom401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DownloadRom401JSONResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DownloadRom404JSONResponse struct{ NotFoundJSONResponse }

func (response DownloadRom404JSONResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DownloadRom416JSONResponse Error

func (response DownloadRom416JSONResponse) VisitDownloadRomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(416)

	return json.NewEncoder(w).Encode(response)
}

type ConnectWebSocketRequestObject struct {
}

type ConnectWebSocketResponseObject interface {
	VisitConnectWebSocketResponse(w http.ResponseWriter) error
}

type ConnectWebSocket101Response struct {
}

func (response ConnectWebSocket101Response) VisitConnectWebSocketResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type ConnectWebSocket401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ConnectWebSocket401JSONResponse) VisitConnectWebSocketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Hub-Info (ohne Auth, verleiht keine Rechte)
	// (GET /.well-known/framebeam)
	GetHubInfo(ctx context.Context, request GetHubInfoRequestObject) (GetHubInfoResponseObject, error)
	// Gerät widerruft sich selbst
	// (POST /api/v1/auth/revoke)
	RevokeSelf(ctx context.Context, request RevokeSelfRequestObject) (RevokeSelfResponseObject, error)
	// Access Token gegen Device Credential tauschen
	// (POST /api/v1/auth/token)
	CreateAccessToken(ctx context.Context, request CreateAccessTokenRequestObject) (CreateAccessTokenResponseObject, error)
	// Spielebibliothek
	// (GET /api/v1/games)
	ListGames(ctx context.Context, request ListGamesRequestObject) (ListGamesResponseObject, error)
	// Einzelnes Spiel
	// (GET /api/v1/games/{game_id})
	GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error)
	// Handshake mit Capability Negotiation
	// (POST /api/v1/handshake)
	PostHandshake(ctx context.Context, request PostHandshakeRequestObject) (PostHandshakeResponseObject, error)
	// Pairing-Anfrage stellen (Admin entscheidet Allow/Deny)
	// (POST /api/v1/pairing/requests)
	CreatePairingRequest(ctx context.Context, request CreatePairingRequestRequestObject) (CreatePairingRequestResponseObject, error)
	// Status der Pairing-Anfrage abfragen (Bearer = poll_token)
	// (GET /api/v1/pairing/requests/{request_id})
	GetPairingRequest(ctx context.Context, request GetPairingRequestRequestObject) (GetPairingRequestResponseObject, error)
	// ROM-Download (Range-Unterstützung). Upload nur über das Admin-Webinterface.
	// (GET /api/v1/roms/{sha256})
	DownloadRom(ctx context.Context, request DownloadRomRequestObject) (DownloadRomResponseObject, error)
	// WSS-Upgrade (nur Dokumentation, Implementierung folgt)
	// (GET /api/v1/ws)
	ConnectWebSocket(ctx context.Context, request ConnectWebSocketRequestObject) (ConnectWebSocketResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHubInfo operation middleware
func (sh *strictHandler) GetHubInfo(w http.ResponseWriter, r *http.Request) {
	var request GetHubInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHubInfo(ctx, request.(GetHubInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHubInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHubInfoResponseObject); ok {
		if err := validResponse.VisitGetHubInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeSelf operation middleware
func (sh *strictHandler) RevokeSelf(w http.ResponseWriter, r *http.Request) {
	var request RevokeSelfRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeSelf(ctx, request.(RevokeSelfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeSelf")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeSelfResponseObject); ok {
		if err := validResponse.VisitRevokeSelfResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccessToken operation middleware
func (sh *strictHandler) CreateAccessToken(w http.ResponseWriter, r *http.Request) {
	var request CreateAccessTokenRequestObject

	var body CreateAccessTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccessToken(ctx, request.(CreateAccessTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccessToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccessTokenResponseObject); ok {
		if err := validResponse.VisitCreateAccessTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGames operation middleware
func (sh *strictHandler) ListGames(w http.ResponseWriter, r *http.Request) {
	var request ListGamesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGames(ctx, request.(ListGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGamesResponseObject); ok {
		if err := validResponse.VisitListGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGame operation middleware
func (sh *strictHandler) GetGame(w http.ResponseWriter, r *http.Request, gameId openapi_types.UUID) {
	var request GetGameRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGame(ctx, request.(GetGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameResponseObject); ok {
		if err := validResponse.VisitGetGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostHandshake operation middleware
func (sh *strictHandler) PostHandshake(w http.ResponseWriter, r *http.Request) {
	var request PostHandshakeRequestObject

	var body PostHandshakeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostHandshake(ctx, request.(PostHandshakeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostHandshake")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostHandshakeResponseObject); ok {
		if err := validResponse.VisitPostHandshakeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePairingRequest operation middleware
func (sh *strictHandler) CreatePairingRequest(w http.ResponseWriter, r *http.Request) {
	var request CreatePairingRequestRequestObject

	var body CreatePairingRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePairingRequest(ctx, request.(CreatePairingRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePairingRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePairingRequestResponseObject); ok {
		if err := validResponse.VisitCreatePairingRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPairingRequest operation middleware
func (sh *strictHandler) GetPairingRequest(w http.ResponseWriter, r *http.Request, requestId openapi_types.UUID) {
	var request GetPairingRequestRequestObject

	request.RequestId = requestId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPairingRequest(ctx, request.(GetPairingRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPairingRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPairingRequestResponseObject); ok {
		if err := validResponse.VisitGetPairingRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadRom operation middleware
func (sh *strictHandler) DownloadRom(w http.ResponseWriter, r *http.Request, sha256 string, params DownloadRomParams) {
	var request DownloadRomRequestObject

	request.Sha256 = sha256
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadRom(ctx, request.(DownloadRomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadRom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadRomResponseObject); ok {
		if err := validResponse.VisitDownloadRomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConnectWebSocket operation middleware
func (sh *strictHandler) ConnectWebSocket(w http.ResponseWriter, r *http.Request) {
	var request ConnectWebSocketRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConnectWebSocket(ctx, request.(ConnectWebSocketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConnectWebSocket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConnectWebSocketResponseObject); ok {
		if err := validResponse.VisitConnectWebSocketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
